# Generated by Django 5.1.4 on 2024-12-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='code_product',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
