# Generated by Django 5.1.4 on 2024-12-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
